### ISSUE TITLE
Port 35729 is already in use by another process

### ISSUE THREAD

**Issue by b4z81** [toddmotto/fireshell#39]
grunt-dev.command return this error:

<pre>
Running "connect:livereload" (connect) task
Started connect web server on localhost:9000.

Running "open:server" (open) task

Running "watch" task
Waiting...Fatal error: Port 35729 is already in use by another process.
logout
</pre>

if i display the list of open network connections:

<pre>
Sublime   1156 macbookpro    7u  IPv4 0xffffff801a66ba40      0t0  TCP *:35729 (LISTEN)
</pre>

**Comment by heaversm** [comment]
Had to run `sudo lsof -i :35729` in mac terminal to get it to list the offender - virtualbox for me.

**Comment by kalgar92** [comment]
Well done ty :+1:

**Comment by nicolae-olariu** [comment]
Thank you @heaversm. The trick did it for me too! (Ubuntu 14.10)

**Comment by pengbits** [comment]
hipchat was running on 9000 for me - so changing the port in gruntfile did the trick

**Comment by vickyonit** [comment]
For me it was because of ioniclabs! found it using $ lsof grep | 35729

**Comment by kannan-chandra** [comment]
+1 Sublime

**Comment by op1ekun** [comment]
Hi everyone. I run into dreaded `Fatal error: Port 35729 is already in use by another process.`

I'm testing this configuration:

```
concurrent: {
    options: {
        logConcurrentOutput: true
    },
    tests: {
        tasks: ['watch:scripts', 'watch:css', 'watch:tests']
    },
    codes: {
        tasks: ['watch:scripts', 'watch:css']
    }
}
```

followed by:

```
grunt.registerTask('develop:tests', ['concurrent:tests']);
grunt.registerTask('develop:codes', ['concurrent:codes']);

grunt.registerTask('default', [ 'develop:codes' ]);
```

I'm on Windows Server 2012 R2
using gitbash

I have no LiveReload plugin in Sublime nor Webstorm.
I have no other tabs open.
The `netstat` command doesn't show anything that uses port `35729`.

Basically I have only my gitbash command line open, and it still doesn't work :cry: 

I would appreciate any help...

**Comment by raua** [comment]
To solve this, I just need to close my firefox, sublime text and my terminal. After works well.

**Comment by versido** [comment]
Is the problem similar with Apache port interrupted after installing Nginx? then we should configure the ports to be different? I have met the problem after installing Livereload package for my sublime, and it was made _Fatal error: Port 35729 is already in use by another process. _appeared when i am running grunt serve to my yeoman project which has grunt-contrib-connect integration with Livereload Chrome Extension.

**Comment by mrjonah** [comment]
I had the same issue, saw grunt process was running multiple times, killed both and everything restarted just fine.

**Comment by karthikeyana** [comment]
Check which process is listening on that port using:
fuser  port_no/tcp
then kill that process using
kill -9 pid

**Comment by umair-khanzada** [comment]
it's happening some time cause of other terminal window is open.
solution thats works for me is:
1) Close all terminal windows and then run project again.
2) Close terminal && Restat IDE.

**Comment by gunjot-mansa** [comment]
thanks to @cmplank 
stackoverflow.com tab in Chrome
- UPDATE -seems some other issue again!

**Comment by leotm** [comment]
I only get it when LiveReload is already running in the background, with the LiveReload package installed.

Closing LiveReload the opening Sublime fixes it for me.

**Comment by shiziqiu** [comment]
yes
