### ISSUE TITLE
What is the purpose/intended use of src/scss/vendor/_external.scss? 

### ISSUE THREAD

**Issue by tconroy** [toddmotto/fireshell#72]
Is it to import styles provided by vendors (ie from a bower package)? If so, why does normalize.css get placed directly into the components folder, as opposed to `@included` here?

**Comment by miduku** [comment]
I believe it's for things such as font-awesome, etc. Things you @import to your style.scss. 
normalize.css is added to the css automatically through grunt and is therfore a component (?).
For me CSS from vendors folder is easier to add to the stylesheet than changing the gruntfile.

Correct me if I'm wrong.
